version: '3.8'

# Docker Compose específico para Redis com configurações corretas
# Uso: docker-compose -f docker-compose.redis.yml up -d

services:
  redis:
    image: redis:alpine
    container_name: redis_redis  # Nome do container para corresponder ao host
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass 85Gfts3
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "85Gfts3", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - redis_data:/data
    networks:
      - sdr_network
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  redis_data:
    driver: local

networks:
  sdr_network:
    driver: bridge
    name: sdr_network