name: Deploy to Production

on:
  push:
    branches: [ deploy ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: sdr-ia-solarprime
  DOCKER_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        # Add your tests here
        python -m pytest tests/ || true

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        docker build -t $DOCKER_IMAGE:$DOCKER_TAG -f prod/Dockerfile .
    
    - name: Save Docker image
      run: |
        docker save $DOCKER_IMAGE:$DOCKER_TAG > image.tar
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: image.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deploy'
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy notification
      run: |
        echo "🚀 Deploying SDR IA SolarPrime v0.2 to production!"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        echo "Time: $(date)"
    
    # Add your deployment steps here
    # Examples:
    # - Deploy to VPS via SSH
    # - Deploy to cloud provider
    # - Update EasyPanel
    # - Send webhook notification